name: crypto-tracker

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?falta en .env}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?falta en .env}
      POSTGRES_DB: ${POSTGRES_DB:?falta en .env}

    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  backend:
    build: ../backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      CORS_ORIGINS: ${CORS_ORIGINS:?falta en .env}
      BINANCE_REST_URL: ${BINANCE_REST_URL:?falta en .env}
      DATABASE_URL: ${DATABASE_URL:?falta en .env}
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ../backend:/code
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: